import { describe, expect, it } from "vitest"
import { renderHelperSource } from "../src/main/hooks/install.js"
import { HOOK_SIGNAL_HELPER_VERSION, HOOK_SIGNAL_SCHEMA_VERSION } from "../src/main/hooks/signals.js"

/**
 * The hook helper is authored as a JS-valid `.mjs` template inlined `?raw`, so
 * its SCHEMA_VERSION / HELPER_VERSION are literals in the template rather than
 * interpolated from signals.ts. Pin them to the canonical constants so the two
 * can't drift — and, since rendering the source pulls the `?raw` import, this
 * also asserts the template resolves and ships under the test runner.
 */
describe("arc-hook-signal helper source", () => {
  it("ships the schema/helper versions signals.ts declares", () => {
    const src = renderHelperSource()
    expect(src).toContain(`const SCHEMA_VERSION = ${HOOK_SIGNAL_SCHEMA_VERSION}`)
    expect(src).toContain(`const HELPER_VERSION = ${HOOK_SIGNAL_HELPER_VERSION}`)
  })

  it("carries the generated do-not-edit header for the runtime copy", () => {
    expect(renderHelperSource().startsWith("// Generated by Arc Work. Do not edit.\n")).toBe(true)
  })
})
