import { Effect } from "effect"
import * as fs from "node:fs"
import * as path from "node:path"
import { ArcEnvTags } from "../../shared/env-tags.js"
import {
  ARC_HOOK_SOCK_ENV,
  HELPER_FILENAME,
  HOOK_SIGNAL_HELPER_VERSION,
  HOOK_SIGNAL_SCHEMA_VERSION,
  arcOwnedHelperFile,
} from "./signals.js"

/**
 * Installs hook plumbing so target CLIs announce lifecycle and tool events to
 * arc. Two artifacts:
 *   1. the helper script in the Arc-owned runtime dir
 *      (`~/.arcwork/<profile>/runtime/`, outside any repo — one copy per
 *      profile, regenerated when its version changes)
 *   2. provider hook config the CLI reads, pointing at that Arc-owned helper
 *
 * Only (2) currently touches the repo (`.claude`/`.codex`/`.cursor`); relocating
 * those out of the repo is tracked separately. The helper itself no longer lands
 * in the workspace, so it can never dirty `git status`.
 *
 * Best-effort by contract (Codex tightening #2): a failure returns a reason so
 * the caller can log that native binding is unavailable, but never blocks launch.
 */

/** The helper, rendered with the env-var names interpolated so there is one
 * source of truth (shared/env-tags.ts). It connects to the injected socket and
 * writes one line, then exits 0 — hooks must never block or fail the CLI. */
const renderHelperSource = (): string => `// Generated by arc-electron. Do not edit.
// Invoked by a target CLI hook: \`node <this> <provider> <event>\`.
// Ships the raw hook payload + inherited Arc tags to main over a unix socket.
import net from "node:net"
import { createHash } from "node:crypto"

const SCHEMA_VERSION = ${HOOK_SIGNAL_SCHEMA_VERSION}
const HELPER_VERSION = ${HOOK_SIGNAL_HELPER_VERSION}
const sock = process.env[${JSON.stringify(ARC_HOOK_SOCK_ENV)}]
const [, , declaredProvider = "unknown", declaredEvent = "unknown"] = process.argv

const chunks = []
for await (const chunk of process.stdin) chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk)
const stdinBytes = Buffer.concat(chunks)
const stdinText = stdinBytes.toString("utf8")

const isRecord = (v) => typeof v === "object" && v !== null && !Array.isArray(v)
const str = (v) => typeof v === "string" && v.length > 0 ? v : null
const firstStr = (obj, keys) => {
  if (!isRecord(obj)) return null
  for (const key of keys) {
    const v = str(obj[key])
    if (v) return v
  }
  return null
}

let hookInput = stdinText
let hookInputParseOk = false
try {
  hookInput = JSON.parse(stdinText)
  hookInputParseOk = true
} catch {}

const hookInputObj = isRecord(hookInput) ? hookInput : null
const native = {
  sessionId: firstStr(hookInputObj, ["session_id", "sessionId", "sessionID"]),
  transcriptPath: firstStr(hookInputObj, ["transcript_path", "transcriptPath"]),
  conversationId: firstStr(hookInputObj, ["conversation_id", "conversationId"]),
  turnId: firstStr(hookInputObj, ["turn_id", "turnId"]),
  toolUseId: firstStr(hookInputObj, ["tool_use_id", "toolUseId"]),
  hookEventName: firstStr(hookInputObj, ["hook_event_name", "hookEventName"]),
  model: str(hookInputObj?.model),
}

const record = {
  schemaVersion: SCHEMA_VERSION,
  helperVersion: HELPER_VERSION,
  declaredProvider,
  declaredEvent,
  observedAt: new Date().toISOString(),
  cwd: process.cwd(),
  pid: process.pid,
  argv: process.argv,
  hookInput,
  hookInputParseOk,
  hookInputSha256: createHash("sha256").update(stdinBytes).digest("hex"),
  native,
  arc: {
    chatId: process.env[${JSON.stringify(ArcEnvTags.chatId)}] ?? null,
    targetSessionId: process.env[${JSON.stringify(ArcEnvTags.targetSessionId)}] ?? null,
    targetProvider: process.env[${JSON.stringify(ArcEnvTags.targetProvider)}] ?? null,
    hookSockPresent: Boolean(sock),
  },
  // Legacy flat fields for transitional readers.
  provider: declaredProvider,
  event: declaredEvent,
  at: new Date().toISOString(),
  sessionId: native.sessionId ?? native.conversationId,
  arcChatSessionId: process.env[${JSON.stringify(ArcEnvTags.chatId)}] ?? null,
  arcTargetSessionId: process.env[${JSON.stringify(ArcEnvTags.targetSessionId)}] ?? null,
  arcTargetProvider: process.env[${JSON.stringify(ArcEnvTags.targetProvider)}] ?? null,
}

if (sock) {
  await new Promise((resolve) => {
    const c = net.createConnection(sock)
    c.on("connect", () => c.end(JSON.stringify(record) + "\\n"))
    c.on("close", resolve)
    c.on("error", resolve) // best-effort: never block the CLI
  })
}
process.exit(0)
`

const settingsLocalFile = (repoRoot: string): string =>
  path.join(repoRoot, ".claude", "settings.local.json")
const codexHooksFile = (repoRoot: string): string => path.join(repoRoot, ".codex", "hooks.json")
const cursorHooksFile = (repoRoot: string): string => path.join(repoRoot, ".cursor", "hooks.json")

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null

/** Read existing hook config without clobbering user-authored files. */
function readJsonObject(file: string): Record<string, unknown> {
  let root: Record<string, unknown> = {}
  if (fs.existsSync(file)) {
    try {
      const parsed: unknown = JSON.parse(fs.readFileSync(file, "utf8"))
      if (isRecord(parsed)) root = parsed
    } catch {
      // Unparseable settings: leave the file alone rather than clobber it.
      throw new Error(`existing ${path.basename(file)} is not valid JSON`)
    }
  }
  return root
}

function writeJsonObject(file: string, root: Record<string, unknown>): void {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, `${JSON.stringify(root, null, 2)}\n`)
}

function quotedCommand(helperPath: string, provider: string, event: string): string {
  return `node ${JSON.stringify(helperPath)} ${provider} ${event}`
}

/** Every command string reachable from a hook block, whether it carries the
 * command directly (cursor) or nests it under `hooks[]` (claude/codex). */
function commandStringsOf(block: unknown): Array<string> {
  if (!isRecord(block)) return []
  const out: Array<string> = []
  if (typeof block["command"] === "string") out.push(block["command"])
  if (Array.isArray(block["hooks"])) {
    for (const h of block["hooks"]) {
      if (isRecord(h) && typeof h["command"] === "string") out.push(h["command"])
    }
  }
  return out
}

/**
 * Whether a single command string is one Arc installs: `node <path> <provider>
 * <event>` whose script argument *is* our helper (basename {@link
 * HELPER_FILENAME}), regardless of the absolute path in front of it — that path
 * is what changes across the repo-local → Arc-owned move.
 *
 * Shape-aware on purpose. A loose `command.includes("arc-hook-signal.mjs")`
 * would also flag a user's own command that merely mentions the filename
 * (`./log.sh arc-hook-signal.mjs`, `cat notes-arc-hook-signal.mjs`); matching
 * the `node <script>` position avoids clobbering those.
 */
export const isArcCommand = (command: string): boolean => {
  const m = command.match(/^node\s+("(?:[^"\\]|\\.)*"|\S+)/)
  if (!m) return false
  let script = m[1]!
  if (script.startsWith('"')) {
    try {
      script = JSON.parse(script) as string
    } catch {
      script = script.slice(1, -1)
    }
  }
  return path.basename(script) === HELPER_FILENAME
}

/** Does this block contain *any* Arc-installed command? (Predicate for tests /
 * diagnostics; pruning itself is command-level, see {@link replaceArcBlock}.) */
export const isArcBlock = (block: unknown): boolean =>
  commandStringsOf(block).some(isArcCommand)

/**
 * Strip Arc's own command(s) out of one existing block, returning the block to
 * keep — or `null` when it was a pure-Arc block now left empty. A user command
 * sharing a block with Arc's (combined under one matcher, or a flat cursor
 * entry) survives: pruning is per-command, not per-block.
 */
function stripArcFromBlock(block: Record<string, unknown>): Record<string, unknown> | null {
  let next = block
  let changed = false
  if (typeof next["command"] === "string" && isArcCommand(next["command"])) {
    const { command: _arc, ...rest } = next
    next = rest
    changed = true
  }
  if (Array.isArray(next["hooks"])) {
    const filtered = next["hooks"].filter(
      (h) => !(isRecord(h) && typeof h["command"] === "string" && isArcCommand(h["command"])),
    )
    if (filtered.length !== next["hooks"].length) {
      next = { ...next, hooks: filtered }
      changed = true
    }
  }
  if (!changed) return block // no Arc command here — leave the user block untouched
  return commandStringsOf(next).length > 0 ? next : null // drop only if nothing user-owned remains
}

/** Prune Arc's prior command(s) from every existing block, then install the
 * current one as its own block. User blocks — and user commands sharing a block
 * with Arc's — are preserved. */
export function replaceArcBlock(
  existing: unknown,
  freshBlock: Record<string, unknown>,
): Array<Record<string, unknown>> {
  const kept = (Array.isArray(existing) ? existing : [])
    .filter(isRecord)
    .map(stripArcFromBlock)
    .filter((b): b is Record<string, unknown> => b !== null)
  kept.push(freshBlock)
  return kept
}

const CLAUDE_EVENTS = [
  "SessionStart", "Setup", "SessionEnd",
  "UserPromptSubmit", "UserPromptExpansion",
  "PreToolUse", "PermissionRequest", "PermissionDenied",
  "PostToolUse", "PostToolUseFailure", "PostToolBatch",
  "Notification", "MessageDisplay",
  "SubagentStart", "SubagentStop", "TaskCreated", "TaskCompleted", "TeammateIdle",
  "Stop", "StopFailure",
  "InstructionsLoaded", "ConfigChange", "CwdChanged",
  "WorktreeCreate", "WorktreeRemove",
  "PreCompact", "PostCompact",
] as const

const CODEX_EVENTS = [
  "SessionStart",
  "UserPromptSubmit",
  "PreToolUse",
  "PermissionRequest",
  "PostToolUse",
  "PreCompact",
  "PostCompact",
  "SubagentStart",
  "SubagentStop",
  "Stop",
] as const

const CURSOR_EVENTS = [
  "sessionStart", "sessionEnd", "workspaceOpen",
  "beforeSubmitPrompt",
  "preToolUse", "postToolUse", "postToolUseFailure",
  "beforeShellExecution", "afterShellExecution",
  "beforeMCPExecution", "afterMCPExecution",
  "beforeReadFile", "afterFileEdit", "beforeTabFileRead", "afterTabFileEdit",
  "subagentStart", "subagentStop",
  "preCompact",
  "afterAgentResponse", "afterAgentThought", "stop",
] as const

function mergeClaudeHooks(file: string, helperPath: string): void {
  const root = readJsonObject(file)
  const hooks = isRecord(root["hooks"]) ? (root["hooks"] as Record<string, unknown>) : {}
  const nextHooks = { ...hooks }
  for (const event of CLAUDE_EVENTS) {
    const command = quotedCommand(helperPath, "claude", event)
    nextHooks[event] = replaceArcBlock(nextHooks[event], { matcher: "", hooks: [{ type: "command", command }] })
  }
  writeJsonObject(file, { ...root, hooks: nextHooks })
}

function mergeCodexHooks(file: string, helperPath: string): void {
  const root = readJsonObject(file)
  const hooks = isRecord(root["hooks"]) ? (root["hooks"] as Record<string, unknown>) : {}
  const nextHooks = { ...hooks }
  for (const event of CODEX_EVENTS) {
    const command = quotedCommand(helperPath, "codex", event)
    nextHooks[event] = replaceArcBlock(nextHooks[event], { hooks: [{ type: "command", command }] })
  }
  writeJsonObject(file, { ...root, hooks: nextHooks })
}

function mergeCursorHooks(file: string, helperPath: string): void {
  const root = readJsonObject(file)
  const hooks = isRecord(root["hooks"]) ? (root["hooks"] as Record<string, unknown>) : {}
  const nextHooks = { ...hooks }
  for (const event of CURSOR_EVENTS) {
    const command = quotedCommand(helperPath, "cursor", event)
    nextHooks[event] = replaceArcBlock(nextHooks[event], { command })
  }
  writeJsonObject(file, {
    ...root,
    version: root["version"] ?? 1,
    hooks: nextHooks,
    _arcNote: "arc-electron installed repo-local hook observers; hooks are best-effort and should not affect CLI behavior.",
  })
}

export interface InstallResult {
  readonly installed: boolean
  readonly reason?: string
}

/**
 * Write the Arc-owned helper + merge the provider's hook config to point at it.
 * Best-effort: the I/O can throw (read-only FS, unparseable user settings), so
 * this is `Effect.try` rather than `Effect.sync`, and `Effect.match` folds both
 * channels into an {@link InstallResult} — the caller is told native binding is
 * unavailable, but launch is never blocked.
 */
export const installProviderHooks = (
  repoRoot: string,
  provider: string,
  env: NodeJS.ProcessEnv = process.env,
): Effect.Effect<InstallResult> =>
  Effect.try({
    try: () => {
      const helperPath = arcOwnedHelperFile(env)
      fs.mkdirSync(path.dirname(helperPath), { recursive: true })
      fs.writeFileSync(helperPath, renderHelperSource())
      if (provider === "claude") mergeClaudeHooks(settingsLocalFile(repoRoot), helperPath)
      else if (provider === "codex") mergeCodexHooks(codexHooksFile(repoRoot), helperPath)
      else if (provider === "cursor") mergeCursorHooks(cursorHooksFile(repoRoot), helperPath)
    },
    catch: (cause) => (cause instanceof Error ? cause.message : String(cause)),
  }).pipe(
    Effect.match({
      onSuccess: (): InstallResult => ({ installed: true }),
      onFailure: (reason): InstallResult => ({ installed: false, reason }),
    }),
  )
