import { Effect } from "effect"
import * as fs from "node:fs"
import * as path from "node:path"
import { ArcEnvTags } from "../../shared/env-tags.js"
import {
  ARC_HOOK_SOCK_ENV,
  HELPER_FILENAME,
  HOOK_SIGNAL_HELPER_VERSION,
  HOOK_SIGNAL_SCHEMA_VERSION,
  helperFile,
  runtimeDir,
} from "./signals.js"

/**
 * Installs hook plumbing into a workspace so target CLIs announce lifecycle and
 * tool events to arc. Two artifacts:
 *   1. the helper script in `<repoRoot>/.arc/runtime/` (gitignored)
 *   2. repo-local provider hook config
 *      (gitignored — arc's instrumentation never shows up in `git status`)
 *
 * Best-effort by contract (Codex tightening #2): a failure returns a reason so
 * the caller can log that native binding is unavailable, but never blocks launch.
 */

/** The helper, rendered with the env-var names interpolated so there is one
 * source of truth (shared/env-tags.ts). It connects to the injected socket and
 * writes one line, then exits 0 — hooks must never block or fail the CLI. */
const renderHelperSource = (): string => `// Generated by arc-electron. Do not edit.
// Invoked by a target CLI hook: \`node <this> <provider> <event>\`.
// Ships the raw hook payload + inherited Arc tags to main over a unix socket.
import net from "node:net"
import { createHash } from "node:crypto"

const SCHEMA_VERSION = ${HOOK_SIGNAL_SCHEMA_VERSION}
const HELPER_VERSION = ${HOOK_SIGNAL_HELPER_VERSION}
const sock = process.env[${JSON.stringify(ARC_HOOK_SOCK_ENV)}]
const [, , declaredProvider = "unknown", declaredEvent = "unknown"] = process.argv

const chunks = []
for await (const chunk of process.stdin) chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk)
const stdinBytes = Buffer.concat(chunks)
const stdinText = stdinBytes.toString("utf8")

const isRecord = (v) => typeof v === "object" && v !== null && !Array.isArray(v)
const str = (v) => typeof v === "string" && v.length > 0 ? v : null
const firstStr = (obj, keys) => {
  if (!isRecord(obj)) return null
  for (const key of keys) {
    const v = str(obj[key])
    if (v) return v
  }
  return null
}

let hookInput = stdinText
let hookInputParseOk = false
try {
  hookInput = JSON.parse(stdinText)
  hookInputParseOk = true
} catch {}

const hookInputObj = isRecord(hookInput) ? hookInput : null
const native = {
  sessionId: firstStr(hookInputObj, ["session_id", "sessionId", "sessionID"]),
  transcriptPath: firstStr(hookInputObj, ["transcript_path", "transcriptPath"]),
  conversationId: firstStr(hookInputObj, ["conversation_id", "conversationId"]),
  turnId: firstStr(hookInputObj, ["turn_id", "turnId"]),
  toolUseId: firstStr(hookInputObj, ["tool_use_id", "toolUseId"]),
  hookEventName: firstStr(hookInputObj, ["hook_event_name", "hookEventName"]),
  model: str(hookInputObj?.model),
}

const record = {
  schemaVersion: SCHEMA_VERSION,
  helperVersion: HELPER_VERSION,
  declaredProvider,
  declaredEvent,
  observedAt: new Date().toISOString(),
  cwd: process.cwd(),
  pid: process.pid,
  argv: process.argv,
  hookInput,
  hookInputParseOk,
  hookInputSha256: createHash("sha256").update(stdinBytes).digest("hex"),
  native,
  arc: {
    chatId: process.env[${JSON.stringify(ArcEnvTags.chatId)}] ?? null,
    targetSessionId: process.env[${JSON.stringify(ArcEnvTags.targetSessionId)}] ?? null,
    targetProvider: process.env[${JSON.stringify(ArcEnvTags.targetProvider)}] ?? null,
    hookSockPresent: Boolean(sock),
  },
  // Legacy flat fields for transitional readers.
  provider: declaredProvider,
  event: declaredEvent,
  at: new Date().toISOString(),
  sessionId: native.sessionId ?? native.conversationId,
  arcChatSessionId: process.env[${JSON.stringify(ArcEnvTags.chatId)}] ?? null,
  arcTargetSessionId: process.env[${JSON.stringify(ArcEnvTags.targetSessionId)}] ?? null,
  arcTargetProvider: process.env[${JSON.stringify(ArcEnvTags.targetProvider)}] ?? null,
}

if (sock) {
  await new Promise((resolve) => {
    const c = net.createConnection(sock)
    c.on("connect", () => c.end(JSON.stringify(record) + "\\n"))
    c.on("close", resolve)
    c.on("error", resolve) // best-effort: never block the CLI
  })
}
process.exit(0)
`

const settingsLocalFile = (repoRoot: string): string =>
  path.join(repoRoot, ".claude", "settings.local.json")
const codexHooksFile = (repoRoot: string): string => path.join(repoRoot, ".codex", "hooks.json")
const cursorHooksFile = (repoRoot: string): string => path.join(repoRoot, ".cursor", "hooks.json")

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null

/** Read existing hook config without clobbering user-authored files. */
function readJsonObject(file: string): Record<string, unknown> {
  let root: Record<string, unknown> = {}
  if (fs.existsSync(file)) {
    try {
      const parsed: unknown = JSON.parse(fs.readFileSync(file, "utf8"))
      if (isRecord(parsed)) root = parsed
    } catch {
      // Unparseable settings: leave the file alone rather than clobber it.
      throw new Error(`existing ${path.basename(file)} is not valid JSON`)
    }
  }
  return root
}

function writeJsonObject(file: string, root: Record<string, unknown>): void {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, `${JSON.stringify(root, null, 2)}\n`)
}

function quotedCommand(repoRoot: string, provider: string, event: string): string {
  return `node ${JSON.stringify(helperFile(repoRoot))} ${provider} ${event}`
}

function appendUniqueClaudeBlock(existing: unknown, command: string): Array<Record<string, unknown>> {
  const blocks = Array.isArray(existing) ? [...existing] : []
  const alreadyInstalled = blocks.some(
    (block) =>
      isRecord(block) &&
      Array.isArray(block["hooks"]) &&
      (block["hooks"] as Array<unknown>).some(
        (h) => isRecord(h) && typeof h["command"] === "string" && h["command"].includes(command),
      ),
  )
  if (!alreadyInstalled) blocks.push({ matcher: "", hooks: [{ type: "command", command }] })
  return blocks as Array<Record<string, unknown>>
}

function appendUniqueCursorBlock(existing: unknown, command: string): Array<Record<string, unknown>> {
  const blocks = Array.isArray(existing) ? [...existing] : []
  const alreadyInstalled = blocks.some(
    (block) =>
      isRecord(block) &&
      (block["command"] === command ||
        (Array.isArray(block["hooks"]) &&
          (block["hooks"] as Array<unknown>).some(
            (h) => isRecord(h) && typeof h["command"] === "string" && h["command"] === command,
          ))),
  )
  if (!alreadyInstalled) blocks.push({ command })
  return blocks as Array<Record<string, unknown>>
}

function appendUniqueCommandHookBlock(existing: unknown, command: string): Array<Record<string, unknown>> {
  const blocks = Array.isArray(existing) ? [...existing] : []
  const alreadyInstalled = blocks.some(
    (block) =>
      isRecord(block) &&
      Array.isArray(block["hooks"]) &&
      (block["hooks"] as Array<unknown>).some(
        (h) => isRecord(h) && typeof h["command"] === "string" && h["command"] === command,
      ),
  )
  if (!alreadyInstalled) blocks.push({ hooks: [{ type: "command", command }] })
  return blocks as Array<Record<string, unknown>>
}

const CLAUDE_EVENTS = [
  "SessionStart", "Setup", "SessionEnd",
  "UserPromptSubmit", "UserPromptExpansion",
  "PreToolUse", "PermissionRequest", "PermissionDenied",
  "PostToolUse", "PostToolUseFailure", "PostToolBatch",
  "Notification", "MessageDisplay",
  "SubagentStart", "SubagentStop", "TaskCreated", "TaskCompleted", "TeammateIdle",
  "Stop", "StopFailure",
  "InstructionsLoaded", "ConfigChange", "CwdChanged",
  "WorktreeCreate", "WorktreeRemove",
  "PreCompact", "PostCompact",
] as const

const CODEX_EVENTS = [
  "SessionStart",
  "UserPromptSubmit",
  "PreToolUse",
  "PermissionRequest",
  "PostToolUse",
  "PreCompact",
  "PostCompact",
  "SubagentStart",
  "SubagentStop",
  "Stop",
] as const

const CURSOR_EVENTS = [
  "sessionStart", "sessionEnd", "workspaceOpen",
  "beforeSubmitPrompt",
  "preToolUse", "postToolUse", "postToolUseFailure",
  "beforeShellExecution", "afterShellExecution",
  "beforeMCPExecution", "afterMCPExecution",
  "beforeReadFile", "afterFileEdit", "beforeTabFileRead", "afterTabFileEdit",
  "subagentStart", "subagentStop",
  "preCompact",
  "afterAgentResponse", "afterAgentThought", "stop",
] as const

function mergeClaudeHooks(file: string, repoRoot: string): void {
  const root = readJsonObject(file)
  const hooks = isRecord(root["hooks"]) ? (root["hooks"] as Record<string, unknown>) : {}
  const nextHooks = { ...hooks }
  for (const event of CLAUDE_EVENTS) {
    nextHooks[event] = appendUniqueClaudeBlock(nextHooks[event], quotedCommand(repoRoot, "claude", event))
  }
  writeJsonObject(file, { ...root, hooks: nextHooks })
}

function mergeCodexHooks(file: string, repoRoot: string): void {
  const root = readJsonObject(file)
  const hooks = isRecord(root["hooks"]) ? (root["hooks"] as Record<string, unknown>) : {}
  const nextHooks = { ...hooks }
  for (const event of CODEX_EVENTS) {
    nextHooks[event] = appendUniqueCommandHookBlock(nextHooks[event], quotedCommand(repoRoot, "codex", event))
  }
  writeJsonObject(file, { ...root, hooks: nextHooks })
}

function mergeCursorHooks(file: string, repoRoot: string): void {
  const root = readJsonObject(file)
  const hooks = isRecord(root["hooks"]) ? (root["hooks"] as Record<string, unknown>) : {}
  const nextHooks = { ...hooks }
  for (const event of CURSOR_EVENTS) {
    nextHooks[event] = appendUniqueCursorBlock(nextHooks[event], quotedCommand(repoRoot, "cursor", event))
  }
  writeJsonObject(file, {
    ...root,
    version: root["version"] ?? 1,
    hooks: nextHooks,
    _arcNote: "arc-electron installed repo-local hook observers; hooks are best-effort and should not affect CLI behavior.",
  })
}

export interface InstallResult {
  readonly installed: boolean
  readonly reason?: string
}

/** Write the helper + merge provider hook config. Never throws. */
export const installProviderHooks = (repoRoot: string, provider: string): Effect.Effect<InstallResult> =>
  Effect.sync(() => {
    try {
      fs.mkdirSync(runtimeDir(repoRoot), { recursive: true })
      fs.writeFileSync(helperFile(repoRoot), renderHelperSource())
      if (provider === "claude") mergeClaudeHooks(settingsLocalFile(repoRoot), repoRoot)
      else if (provider === "codex") mergeCodexHooks(codexHooksFile(repoRoot), repoRoot)
      else if (provider === "cursor") mergeCursorHooks(cursorHooksFile(repoRoot), repoRoot)
      else return { installed: true }
      return { installed: true }
    } catch (e) {
      return { installed: false, reason: e instanceof Error ? e.message : String(e) }
    }
  })
