import * as fs from "node:fs"
import * as path from "node:path"
import { arcWorkRuntimeDir, resolveProfile } from "../db/paths.js"
import extensionTemplate from "./arc-pi-extension.template.ts?raw"

/**
 * pi integration as a self-registering **extension** (`pi -e <file>`), the
 * cleanest connector of any provider:
 *
 *   - pi has no MCP client, but its extension API registers native tools, so the
 *     extension renders the `arc.*` toolkit directly and bridges each call to
 *     Arc's HTTP MCP — no plugin dir, no `${env:…}` header interpolation, no
 *     approval prompt (the Cursor pain points all vanish).
 *   - pi's typed lifecycle events (`session_start` / `agent_start` / `agent_end`
 *     / `session_shutdown`) are relayed to `ARC_HOOK_SOCK` as Arc's canonical
 *     hook events, so the live-state turn projection and inbox flush-on-idle work
 *     exactly as they do for claude/cursor/codex.
 *
 * The extension reads all of its wiring (bearer, endpoint, hook socket, identity)
 * from the Arc env every launched CLI already gets, so it is **static** — one
 * file per profile, regenerated only when its version changes. Identity rides the
 * env, not the file, so there is nothing per-session to template.
 */

export const ARC_PI_EXTENSION_NAME = "arc-pi-extension.ts"
const ARC_PI_EXTENSION_VERSION = 1

/** The extension dir basename under the Arc-owned runtime. */
export const piExtensionFile = (env: NodeJS.ProcessEnv = process.env): string =>
  path.join(arcWorkRuntimeDir(resolveProfile(env)), ARC_PI_EXTENSION_NAME)

/** The extension source. Authored as real, typed code in
 * `arc-pi-extension.template.ts` (checked against pi's published extension API)
 * and inlined here `?raw` so it survives app packaging. Pure: it reads
 * identity/endpoint from the launch env, so only the version header is dynamic. */
const renderExtensionSource = (): string =>
  `// Generated by Arc Work (v${ARC_PI_EXTENSION_VERSION}). Do not edit.\n${extensionTemplate}`

export interface PiConnectorResult {
  readonly installed: boolean
  readonly file: string
  readonly reason?: string
}

/** Write the Arc-owned pi extension to its profile runtime dir (idempotent).
 * Best-effort and logged by the caller; a failure only means pi launches without
 * the arc tools, never a blocked spawn. */
export const installPiExtension = (env: NodeJS.ProcessEnv = process.env): PiConnectorResult => {
  const file = piExtensionFile(env)
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true })
    fs.writeFileSync(file, renderExtensionSource())
    return { installed: true, file }
  } catch (e) {
    return { installed: false, file, reason: e instanceof Error ? e.message : String(e) }
  }
}

/** Launch argv loading the Arc extension (+ optional model). pi reads its Arc
 * wiring from the env every target gets, so there's nothing else to pass.
 *
 * Default is the interactive TUI — pi is a normal human-drivable PTY provider
 * like claude/cursor/codex (manually launchable, paste-delivered, the inbox
 * pastes follow-ups). `opts.rpc` instead runs the long-lived JSONL server
 * (`--mode rpc`); retained as a usable capability for programmatic/headless
 * drivers even though no provider selects it by default. */
export const piLaunchArgs = (
  extensionFile: string,
  model?: string,
  opts?: { readonly rpc?: boolean },
): ReadonlyArray<string> => [
  ...(opts?.rpc ? ["--mode", "rpc"] : []),
  "-e",
  extensionFile,
  ...(model ? ["--model", model] : []),
]
